### ISSUE TITLE
Broadband layers are failing the SSL check in the proxy

### ISSUE THREAD

**Issue by meh9** [TerriaJS/aremi-natmap#157]
The broadband layers in AREMI are failing to load, looks like they are failing the SSL verification in the proxy. We need to figure out why and fix it, or switch to CORS which is what NationalMap does.

```
{ Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```

**Comment by meh9** [comment]
We switched to CORS.
